### ISSUE TITLE
Package doesn't show in babelEnvDeps.exclude()

### ISSUE THREAD

**Issue by j33n** [AndersDJohnson/webpack-babel-env-deps#10]
I'm using [react-dates](https://github.com/airbnb/react-dates), and when I try logging what's available in babelEnvDeps.exclude(), it's not showing up. Is there a way to enforce it?

Here is the error I was getting before I switched from `exclude: [babelEnvDeps.exclude()]` to `exclude: /node_modules/`

```Error: Couldn't find preset "airbnb" relative to directory```

![image](https://user-images.githubusercontent.com/19430799/48831726-7b9caa00-ed88-11e8-9e12-422d6534db34.png)

**Comment by AndersDJohnson** [comment]
@j33n It looks to me like `react-dates` should be assumed to require transpilation since it does not have an `engines` field nor a `module` or `jsnext:main` key in its `package.json`. I'm not sure why you're getting an error relating to an `airbnb` preset, but I wouldn't think that would have anything to do with this tool. Let me know if you have any updates or figured it out. Thanks!
